Payments Bounded Context
SpineEventEngine/Lobby pull request #17
Opened 2016-11-18 09:21 UTC by dmdashenkov

#### What's done
 - Created `PaymentAggregate` with most of command and event handler methods.
 - Created `PaymentProcessManager` for firing events to the aggregate.
 - Created  repositories for accessing the procman and the aggregate.

#### What's left
 - Complete functionality with redirecting the user to a third-party payment processor (with also posting corresponding events).
 - Complete coverage.

#### Disclaimer
 - **Warning:** this feature isn't complete yet.
 - **Warning:** this branch is forked from `conference-bc`, which is disapproved for merging. Some git rebasing or stashing work must be done when and if this is ready to be merged with `master`.

2016-11-18 09:22 UTC, dmdashenkov commented
@armiol Please, review this code for consistency with Spine ideology.

2016-11-21 13:24 UTC, armiol requested changes
@dmdashenkov let's discuss the architecture vocally.

Also, please see my comments.

2016-11-21 13:24 UTC, armiol commented on .idea/codeStyleSettings.xml
> +        <MarkdownNavigatorCodeStyleSettings>
I think it makes sense to apply the latest code style we have in Spine. So, probably, you'll just need to copy the files from `core-java` repository. And not make any more changes.

2016-11-21 13:24 UTC, armiol commented on payment/src/main/java/org/spine3/samples/lobby/payment/PaymentAggregate.java
> +// TODO:04-11-16:dmytro.dashenkov: Handle wrong addressd case (i.e. ID in command/event does not match aggregate ID).
Typo in `addressd`.

2016-11-21 13:24 UTC, armiol commented on payment/src/main/java/org/spine3/samples/lobby/payment/PaymentAggregate.java
> + * Copyright 2015, TeamDev Ltd. All rights reserved.
It's 2016. The header is wrong.

Copying the `.idea` files from `core-java` will do for the newly created files. But the existing files need to be updated manually.

2016-11-21 13:24 UTC, armiol commented on payment/src/main/java/org/spine3/samples/lobby/payment/PaymentAggregate.java
> +     * Is the aggregate initialized?
The docs should be composed using affirmative sentences only.

2016-11-21 13:24 UTC, armiol commented on payment/src/main/java/org/spine3/samples/lobby/payment/PaymentAggregate.java
> +    public boolean isInitialized() {
I don't like coupling of the aggregate and the process manager.

Let's draw the architecture on the board.

2016-11-21 13:24 UTC, armiol commented on payment/src/main/proto/spine/samples/lobby/payment/procman/procman.proto
> +    spine.samples.lobby.payment.PaymentId aggregateId = 3;
Proto field definition should not use camel case. Use underscore to separate the parts of a field name.

2016-11-21 13:24 UTC, armiol commented on settings.gradle
> +
Why empty line?

2018-09-01 10:09 UTC, dmdashenkov commented
@armiol, it's been quite a while... Maybe, we should close this PR?

2018-10-11 11:15 UTC, dmdashenkov commented
Closing, as this repository is archived.

2018-10-11 11:15 UTC, closed without merging